<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.6 on win32)" generated="20221025 15:17:29.484" rpa="false" schemaversion="3">
<suite id="s1" name="Balance" source="C:\Users\user\Desktop\nuclone\balance.robot">
<test id="s1-t1" name="Show My Balance" line="6">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>http://localhost:6080/</arg>
<arg>chrome</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20221025 15:17:29.812" level="INFO">Opening browser 'chrome' to base url 'http://localhost:6080/'.</msg>
<msg timestamp="20221025 15:17:36.367" level="INFO" html="true">&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan="3"&gt;&lt;a href="selenium-screenshot-2.png"&gt;&lt;img src="selenium-screenshot-2.png" width="800px"&gt;&lt;/a&gt;</msg>
<msg timestamp="20221025 15:17:36.368" level="FAIL">WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=106.0.5249.119)
</msg>
<status status="FAIL" starttime="20221025 15:17:29.812" endtime="20221025 15:17:36.370"/>
</kw>
<kw name="Close Browser" library="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="NOT RUN" starttime="20221025 15:17:36.370" endtime="20221025 15:17:36.370"/>
</kw>
<status status="FAIL" starttime="20221025 15:17:29.811" endtime="20221025 15:17:36.370">WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=106.0.5249.119)
</status>
</test>
<status status="FAIL" starttime="20221025 15:17:29.486" endtime="20221025 15:17:36.370"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Balance">Balance</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
